@HostAddress = http://localhost:5006
@ID=e4827f4c-c1dd-481e-92a3-277ef68d8910

GET {{HostAddress}}/api/board/all
Accept: application/json

###

GET {{HostAddress}}/api/board/{{ID}}
Accept: application/json

###
